Pod2html hash globals 20210312
jkeenan/perl5 pull request #2
Opened 2021-03-28 13:15 UTC by jkeenan

2021-03-31 16:35 UTC, oodler577 approved these changes

2021-04-05 22:15 UTC, rjbs requested changes

2021-04-05 22:15 UTC, rjbs commented on cpan/Pod-Simple/lib/Pod/Simple.pm
> +$VERSION = '3.42_001';
I believe that lines like this are _traditionally_ followed by `$VERSION = eval $VERSION` so that the underscore is seen by code scanning, but the value is, at runtime, usable as a number.

2021-04-05 22:15 UTC, rjbs commented on ext/Pod-Html/lib/Pod/Html.pm
> +    if (  $self->{Htmlroot} eq ''
I can't tell whether the indenting in this file has a method to it, or whether you're just coping with its weirdness.  It seems like indents are changing between 2 and 4 spaces without clear reason.

When the _code_ altering is done, standardizing on one kind of indent is probably a good idea.

2021-04-05 22:15 UTC, rjbs commented on ext/Pod-Html/lib/Pod/Html.pm
> +    my $_updirs_only = ($self->{Podroot} =~ /\.\./) && !($self->{Podroot} =~ /[^\.\\\/]/);
on a line with so many toothpicks, I wonder if `!~` wouldn't be less cognitive load than `!( ... =~ ...)`

2021-04-05 22:15 UTC, rjbs commented on ext/Pod-Html/lib/Pod/Html.pm
> +        $input = *ARGV;
This makes me nervous, but maybe for no reason.  My take is that handling globs directly is almost always a mistake.  I would probably write `$input = *ARGV{IO};` but perhaps that is wrong in some subtle way…

2021-04-05 22:15 UTC, rjbs commented on ext/Pod-Html/lib/Pod/Html.pm
> +sub set_Title {
Normally, I would expect a method named `set_x` to take a new value for `x` as its argument.  This takes a tree from which the title can be extracted.  So, I would call this `set_title_from_podtree`.

2021-04-05 22:15 UTC, rjbs commented on ext/Pod-Html/lib/Pod/Html.pm
> +    my $url = File::Spec::Unix->catfile(Pod::Html::Auxiliary::unixify($self->htmlroot),
`unixify` was made export_ok in Auxiliary, and we import it here, but then it's referred to by fully-qualified name.  Seems like we could save some bytes (and reading complexity) here. :-)

2021-04-05 22:15 UTC, rjbs commented on ext/Pod-Html/lib/Pod/Html/Auxiliary.pm
> +use locale; # make \w work right in non-ASCII lands
I think I'd ask Karl if this is a good idea.  Almost certainly, instead, we should either (a) do nothing or (b) append `/l` to the regex.

2021-04-05 22:15 UTC, rjbs commented on ext/Pod-Html/lib/Pod/Html/Auxiliary.pm
> +    return Pod::Simple::XHTML->can("idify")->(undef, $heading, 1);
This is deeply gross, but I suppose it may as well stay like this, for now.  Getting undef is `$_[0]` allows the `$self->{...}` in the `idify` method to work through autovivification… but it's just so gross.  Still, better to not have to dig around in Pod-Simple, at least for now!

2021-04-05 22:17 UTC, rjbs commented
This is more "request you think about a couple things" than *specific* changes.

Anyway: I tried.  This code is gnarly and the diff is very large.  I think this looks like a huge improvement.  After this is done, I bet another pass or two could yield further improvement, but I wouldn't begrudge you a nice break from looking at this first! ;)

2021-05-12 01:39 UTC, jkeenan commented on cpan/Pod-Simple/lib/Pod/Simple.pm
> +$VERSION = '3.42_001';
`$VERSION = eval $VERSION;` will be done in next pull request.

2021-05-12 01:40 UTC, jkeenan commented on ext/Pod-Html/lib/Pod/Html.pm
> +    if (  $self->{Htmlroot} eq ''
I am planning a series of pull requests.  This sort of tidying should be done in a separate p.r. *after* that series has been merged.

2021-05-12 01:41 UTC, jkeenan commented on ext/Pod-Html/lib/Pod/Html/Auxiliary.pm
> +    return Pod::Simple::XHTML->can("idify")->(undef, $heading, 1);
This is another one of those things that should be considered only after the planned p.r.s have been merged.

2021-05-12 01:45 UTC, jkeenan commented
@rjbs, this particular p.r. won't be merged and eventually will be closed.  Reason: when I came back to this project after two months, I found that the branch which was the basis of the p.r. contained only 14 of the 38 commits!  I have no idea where the other 24 went, even though when I said `git branch --contains pod2html-hash-globals-20210312`, the missing commits were reported as being contained in the branch!

Fortunately, I was able to download the p.r. as a diff and get all 38 commits.  I am now working on a new branch in which I am re-applying those commits one at a time in the hope that I can eliminate some "back-tracking".  Also doing some squashing.  I expect to have this ready to be submitted to the Perl5.git after 5.35.0. is released.

2021-05-12 02:58 UTC, oodler577 commented on ext/Pod-Html/lib/Pod/Html.pm
> +    my $_updirs_only = ($self->{Podroot} =~ /\.\./) && !($self->{Podroot} =~ /[^\.\\\/]/);
not so much cognative load, but a lot less hidden

2021-05-12 03:00 UTC, oodler577 commented
@jkeenan I'm happy to take another look at this when you recreate the PR

2021-05-12 03:03 UTC, oodler577 commented on ext/Pod-Html/lib/Pod/Html.pm
> +    my $url = File::Spec::Unix->catfile(Pod::Html::Auxiliary::unixify($self->htmlroot),
I suppose the question is what does `unixify` mean? Is it a reference to `dos2unix`, i.e., clean up the carriage returns? I have not looked at the implementation just to test my guessing abilities. :^)

2021-05-12 17:59 UTC, jkeenan commented on ext/Pod-Html/lib/Pod/Html.pm
> +sub set_Title {
Will occur in upcoming pull request.

2021-05-12 18:01 UTC, jkeenan commented on ext/Pod-Html/lib/Pod/Html/Auxiliary.pm
> +use locale; # make \w work right in non-ASCII lands
This was Karl's idea in the first place:
```
5f1269ab079 ext/Pod-Html/lib/Pod/Html.pm (Karl Williamson  2014-05-15 21:18:14 -0600  25) use locale; # make \w work right in non-ASCII lands

```
So if you think it's problematic, I'd suggest opening a new issue.  It's outside the scope of what I'm doing.

2021-05-12 18:04 UTC, jkeenan commented on ext/Pod-Html/lib/Pod/Html.pm
> +    my $url = File::Spec::Unix->catfile(Pod::Html::Auxiliary::unixify($self->htmlroot),
Will be included in upcoming p.r.

2021-05-12 18:30 UTC, jkeenan commented on ext/Pod-Html/lib/Pod/Html.pm
> +    my $_updirs_only = ($self->{Podroot} =~ /\.\./) && !($self->{Podroot} =~ /[^\.\\\/]/);
Perhaps we should consult with the author :-)
```
495a00a1 ext/Pod-Html/lib/Pod/Html.pm (Ricardo Signes     2012-03-05 22:31:52 -0500 339)         my $_updirs_only = ($Podroot =~ /\.\./) && !($Podroot =~ /[^\.\\\/]/);
```
This is something I think I'll defer thinking about until I can rig up a way to do coverage analysis and see which paths are actually being exercised.

2021-05-12 18:36 UTC, jkeenan commented on ext/Pod-Html/lib/Pod/Html.pm
> +        $input = *ARGV;
This code originated in this commit:
```
commit 38e30ca7507a601c2d84596bc51d88c0f3c516b4
Author:     Zefram <zefram@fysh.org>
AuthorDate: Wed Dec 13 22:59:28 2017 +0000
```
In order for us to evaluate the statement you cite, we'd have to go back and re-study that entire commit.  That's outside the scope of what I'm doing, so let's defer that until we get the module in better shape overall.

2021-05-13 11:05 UTC, jkeenan commented
Closing this p.r. in favor of https://github.com/jkeenan/perl5/pull/3, https://github.com/jkeenan/perl5/pull/4, https://github.com/jkeenan/perl5/pull/5, https://github.com/jkeenan/perl5/pull/6 and https://github.com/jkeenan/perl5/pull/7.

2021-05-13 11:05 UTC, closed without merging